// <auto-generated />
using DoAnCS_Demo1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCS_Demo1.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("DoAnCS_Demo1.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            email = "cfillery0@hubpages.com",
                            name = "Correy Fillery",
                            password = "rbenrnju)K1R7r'",
                            username = "cfillery0"
                        },
                        new
                        {
                            Id = 2,
                            email = "cninnis1@sogou.com",
                            name = "Casandra Ninnis",
                            password = "avfaxpxu?9!D4'",
                            username = "cninnis1"
                        },
                        new
                        {
                            Id = 3,
                            email = "wwhitely2@businesswire.com",
                            name = "Wiley Whitely",
                            password = "jclrsecgA",
                            username = "wwhitely2"
                        },
                        new
                        {
                            Id = 4,
                            email = "cberwick3@constantcontact.com",
                            name = "Candice Berwick",
                            password = "ihwzuavt",
                            username = "cberwick3"
                        },
                        new
                        {
                            Id = 5,
                            email = "bmarden4@linkedin.com",
                            name = "Beret Marden",
                            password = "uurxsltd1",
                            username = "bmarden4"
                        },
                        new
                        {
                            Id = 6,
                            email = "ajudge5@privacy.gov.au",
                            name = "Alvis Judge",
                            password = "lcehggcko",
                            username = "ajudge5"
                        },
                        new
                        {
                            Id = 7,
                            email = "laneley6@wikispaces.com",
                            name = "Lemuel Aneley",
                            password = "mgkebjqu",
                            username = "laneley6"
                        },
                        new
                        {
                            Id = 8,
                            email = "ikilford7@nationalgeographic.com",
                            name = "Ines Kilford",
                            password = "dkneunzk*5vYc",
                            username = "ikilford7"
                        },
                        new
                        {
                            Id = 9,
                            email = "sschollick8@hud.gov",
                            name = "Shannan Schollick",
                            password = "cnwqiswsPjl6/8u/",
                            username = "sschollick8"
                        },
                        new
                        {
                            Id = 10,
                            email = "rweson9@list-manage.com",
                            name = "Rozanne Weson",
                            password = "wmwjhubsb",
                            username = "rweson9"
                        },
                        new
                        {
                            Id = 11,
                            email = "cbolzena@techcrunch.com",
                            name = "Ches Bolzen",
                            password = "sdnsdtpsZ8&|P@Zu",
                            username = "cbolzena"
                        },
                        new
                        {
                            Id = 12,
                            email = "fohickeeb@quantcast.com",
                            name = "Filippo O'Hickee",
                            password = "rfbygomr6AF9j",
                            username = "fohickeeb"
                        },
                        new
                        {
                            Id = 13,
                            email = "tdomeganc@instagram.com",
                            name = "Teresa Domegan",
                            password = "hzityiykZ",
                            username = "tdomeganc"
                        },
                        new
                        {
                            Id = 14,
                            email = "salmonmacalpine@gmail.com",
                            name = "Salmon MacAlpine",
                            password = "kbvulodh",
                            username = "smacalpined"
                        },
                        new
                        {
                            Id = 15,
                            email = "vgiereke@msu.edu",
                            name = "Valentin Gierek",
                            password = "ulwvqthf.",
                            username = "vgiereke"
                        },
                        new
                        {
                            Id = 16,
                            email = "hduthief@goo.gl",
                            name = "Horten Duthie",
                            password = "wtlpzxqe`=1ek*QU",
                            username = "hduthief"
                        },
                        new
                        {
                            Id = 17,
                            email = "hhengoedg@twitter.com",
                            name = "Holt Hengoed",
                            password = "owraixrwl*_~Pu",
                            username = "hhengoedg"
                        },
                        new
                        {
                            Id = 18,
                            email = "rsacaseh@ezinearticles.com",
                            name = "Renae Sacase",
                            password = "nyimvjgeH5&_m",
                            username = "rsacaseh"
                        },
                        new
                        {
                            Id = 19,
                            email = "egreystokei@pagesperso-orange.fr",
                            name = "Ethelda Greystoke",
                            password = "etysnblfN",
                            username = "egreystokei"
                        },
                        new
                        {
                            Id = 20,
                            email = "hborgbartoloj@netlog.com",
                            name = "Hazel Borg-Bartolo",
                            password = "twfrouhb&.lZ/LWH",
                            username = "hborgbartoloj"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
